[flake8]
max-line-length = 100

[tox]
skip_missing_interpreters = True
envlist = fmt, lint, unit, integration

[vars]
all_path = {[vars]src_path} {[vars]tst_path}
src_path = {toxinidir}/mlflow_exporter
tst_path = {toxinidir}/tests/

[testenv]
setenv =
    PY_COLORS=1

[testenv:update-requirements]
package = skip
commands =
    pip-compile requirements.in
    pip-compile requirements-fmt.in
    pip-compile requirements-lint.in
    pip-compile requirements-integration.in
deps =
    pip-tools
description = Update pinned requirements from all *.in source files.

[testenv:fmt]
package = skip
commands =
    isort {[vars]all_path}
    black {[vars]all_path}
deps =
    -r requirements-fmt.txt
description = Apply coding style standards to code.

[testenv:lint]
package = skip
commands =
    codespell {toxinidir}/. --skip {toxinidir}/./.git --skip {toxinidir}/./.tox \
      --skip {toxinidir}/./build --skip {toxinidir}/./lib --skip {toxinidir}/./venv \
      --skip {toxinidir}/./.mypy_cache \
      --skip {toxinidir}/./icon.svg --skip *.json.tmpl
    pflake8 {[vars]src_path}
    isort --check-only --diff {[vars]all_path}
    black --check --diff {[vars]all_path}
    mypy {[vars]src_path} --ignore-missing-imports
deps =
    -r requirements-lint.txt
    mypy
    types-requests
description = Check code against coding style standards.

[testenv:unit]
package = editable
commands =
    pytest {[vars]tst_path} --ignore={[vars]tst_path}/integration \
      -v --tb native --cov=mlflow_exporter \
      --cov-report=term-missing --cov-report=xml:{toxinidir}/coverage.xml {posargs}
deps =
    pytest
    pytest-cov
description = Run unit tests with coverage.

[testenv:integration]
commands =
    pytest {[vars]tst_path}/integration -vv --tb native --log-cli-level=INFO -s {posargs}
deps =
    -r requirements-integration.txt
description = Run integration tests with a live MLflow server.

