apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow-prometheus-exporter.fullname" . }}
  labels:
    {{- include "mlflow-prometheus-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mlflow-prometheus-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mlflow-prometheus-exporter.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: false
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: exporter
          image: {{ include "mlflow-prometheus-exporter.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "mlflow-prometheus-exporter.fullname" . }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          {{- if or .Values.mlflow.auth.existingSecret (and .Values.mlflow.auth.username .Values.mlflow.auth.password) }}
          env:
            - name: MLFLOW_TRACKING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow-prometheus-exporter.secretName" . }}
                  key: {{ .Values.mlflow.auth.usernameKey }}
            - name: MLFLOW_TRACKING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow-prometheus-exporter.secretName" . }}
                  key: {{ .Values.mlflow.auth.passwordKey }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
