{{- if and .Values.scrapeConfig.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1alpha1/ScrapeConfig") }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ include "mlflow-prometheus-exporter.fullname" . }}
  labels:
    {{- include "mlflow-prometheus-exporter.labels" . | nindent 4 }}
    {{- with .Values.scrapeConfig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  metricsPath: {{ .Values.scrapeConfig.metricsPath | quote }}
  scheme: {{ .Values.scrapeConfig.scheme | quote }}
  scrapeInterval: {{ .Values.scrapeConfig.scrapeInterval | quote }}
  scrapeTimeout: {{ .Values.scrapeConfig.scrapeTimeout | quote }}
  staticConfigs:
    - targets:
        - {{ printf "%s.%s.svc.%s:%d" (include "mlflow-prometheus-exporter.fullname" .) .Release.Namespace .Values.clusterDomain (int .Values.service.port) | quote }}
      labels:
        job: {{ .Values.scrapeConfig.jobLabel | quote }}
        {{- with .Values.scrapeConfig.staticLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
