{{- if and (not .Values.mlflow.auth.existingSecret) (and .Values.mlflow.auth.username .Values.mlflow.auth.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow-prometheus-exporter.secretName" . }}
  labels:
    {{- include "mlflow-prometheus-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.mlflow.auth.usernameKey }}: {{ .Values.mlflow.auth.username | quote }}
  {{ .Values.mlflow.auth.passwordKey }}: {{ .Values.mlflow.auth.password | quote }}
{{- end }}
